name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flask

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -v

      - name: Deploy to Render
        if: success()  # Ne s'exécute que si les tests passent
        run: |
          # Commande de déploiement Render, par exemple :
          render deploy service --name your-service-name --api-key ${{ rnd_mv5QmbXFP64K87yviQTdM4Y98jBb }}
